### ISSUE TITLE
Transitive reusable workflows are not supported

### ISSUE THREAD

**Issue by Virtlink** [metaborg/actions#2]
Using a local workflow in a reusable workflow seems to not be supported. I guess GitHub is looking in the source repository for the workflow, instead of in the workflow repository. This workflow usage:

```
---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    tags:
      - "release-*.*.*"
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: metaborg/workflows/.github/workflows/gradle-build-matrix.yaml@v1
```

Causes [this error](https://github.com/metaborg/gitonium/actions/runs/9222953450/workflow):

> error parsing called workflow
".github/workflows/build.yaml"
-> "metaborg/workflows/.github/workflows/gradle-build-matrix.yaml@v1" (source tag with sha:ed274a69ea568c447985e90340c452362f4ee6bc)
--> "./.github/workflows/gradle-build.yaml"
: workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
